#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status ( for plugged up,  for discharging on battery, etc.).

# Loop through all attached batteries and format the info
for battery in /sys/class/power_supply/BAT?*; do
	# If non-first battery, print a space separator.
	[ -n "${capacity+x}" ] && printf " "
	# Sets up the status and capacity
	case "$(cat "$battery/status")" in
		"Full") status="⚡" ;;
		"Discharging") status=" " ;;
		"Charging") status=" " ;;
		"Not charging"|"Unknown") status=" " ;;
	esac
	capacity=$(cat "$battery/capacity")
	# Will make a warn variable if discharging and low
	[ "$status" = "" ] && [ "$capacity" -le 20 ] && warn=" "
	# Prints the info
	printf "%s%s%d%%" "$status" "$warn" "$capacity"; unset warn
done && exit 0
