#!/bin/sh

# Show wifi 說 and percent strength or 鷺 if none.
# Show  if connected to ethernet or  if none.

case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
	down) wifiicon="鷺 " ;;
	up) wifiicon="$(awk '/^\s*w/ { print "說", int($3 * 100 / 70) "%" }' /proc/net/wireless)" ;;
esac

printf "%s%s%s\n" "$wifiicon" "$(sed "s/down//;s/up//" /sys/class/net/e*/operstate 2>/dev/null)" "$(sed "s/.*/🔒/" /sys/class/net/tun*/operstate 2>/dev/null)"
